trigger:
- main

variables:
- group: Production-Variables

stages:

- stage: CI
  displayName: "Continuous Integration"

  jobs:
  - job: BuildAndTest
    displayName: "Build and Test"

    pool:
      name: Default

    steps:

    # Checkout source code
    - checkout: self

    # Install .NET SDK
    - task: UseDotNet@2
      displayName: "Install .NET SDK"
      inputs:
        packageType: 'sdk'
        version: '$(DOTNET_VERSION)'

    # Restore NuGet packages
    - task: DotNetCoreCLI@2
      displayName: "Restore Packages"
      inputs:
        command: 'restore'
        projects: '**/*.slnx'

    # Build Solution
    - task: DotNetCoreCLI@2
      displayName: "Build Solution"
      inputs:
        command: 'build'
        projects: '**/*.slnx'
        arguments: '--configuration $(BUILD_CONFIGURATION) --no-restore'

    # Run Unit Tests
    - task: DotNetCoreCLI@2
      displayName: "Run Unit Tests"
      inputs:
        command: 'test'
        projects: 'tests/Application.UnitTests/Application.UnitTests.csproj'
        publishTestResults: true
        arguments: '--configuration $(BUILD_CONFIGURATION)'
